README.md

📝 (readme): Cleared fluff, added basic scripts

---

prisma/migrations/20220311085616_adding_test_entity/migration.sql
prisma/schema.prisma

I am adding the Test entity. Please have a look @COS-301/data-engineers @COS-301/developer-operations

🗃️ (prisma): Added Test entity

---

.github/workflows/index.yml

Added the main.yml as a initial Github Actions workflow and foundation to add reusable workflows.
Allows for tests to be triggered on git actions. A useful tool for ensuring the repository has a continuously running build as new code is added.

✔️(CICD): Initial github action yml file

---

.github/workflows/index.yml
.github/workflows/nxtest.yml

Added some yaml clean-up, added the caching of node modules.

✅  Added Caching of Node modules.

---

.github/workflows/nxtest.yml

Updated testing file to include yarn packages.

✅ Added yarn package install

---

.github/workflows/nxtest.yml

Added preface for final testing of project.

✅ Added provisional all test to reusable workflow

---

.github/workflows/nxtest.yml

Reverts COS-301/graduates#242. Errors discovered which cause compilation failure

Revert "✅ Added provisional all test to reusable workflow"

---

CODE_OF_CONDUCT.md

Using the Contributor Covenant (see lines 115 onward)
Given @arneschreuder's email as community leader/contact email

📝(repo): add a code of conduct

---

.github/workflows/nxtest.yml

Revert "Revert "✅ Added provisional all test to reusable workflow""

---

.github/workflows/index.yml

Allows manual trigger of workflow.

💚 Added workflow dispatch

---

libs/client/request-for-access/feature/.eslintrc.json
libs/client/request-for-access/feature/README.md
libs/client/request-for-access/feature/jest.config.js
libs/client/request-for-access/feature/project.json
libs/client/request-for-access/feature/src/index.ts
libs/client/request-for-access/feature/src/lib/request-for-access.component.html
libs/client/request-for-access/feature/src/lib/request-for-access.component.spec.ts
libs/client/request-for-access/feature/src/lib/request-for-access.component.ts
libs/client/request-for-access/feature/src/lib/request-for-access.module.ts
libs/client/request-for-access/feature/src/test-setup.ts
libs/client/request-for-access/feature/tsconfig.json
libs/client/request-for-access/feature/tsconfig.lib.json
libs/client/request-for-access/feature/tsconfig.spec.json
tsconfig.base.json

Setup folder and files for the request-for-access user interface. Added basic mock HTML. Updated feature path in tsconfig.base.json

🤡(ui): Add basic request-for-access interface

---

.github/workflows/index.yml
.github/workflows/metatest.yml

Added file path and triggers for meta tests

✅ (CI/CD) : Added Bases for meta test

---

.github/workflows/metatest.yml

Removed project trigger and added priority label check

✅ (CI/CD) : Added priority label check

---

.github/workflows/metatest.yml

✅ (CI/CD) : Added type check

---

.github/workflows/metatest.yml

Added a test to check status labels

✅ (CI/CD) : Status label check

---

.github/workflows/metatest.yml

Added the checks for scope labels and role labels.

✅ (CI/CD): Added Scope and Role label check

---

.github/workflows/index.yml
.github/workflows/metatest.yml

Added the check for the milestone meta tag.

✅  (CI/CD): Added Milestone check

---

.github/workflows/metatest.yml

Added scope:repository to metatest.yml

✅ (CI/CD): Added scope:repository 

---

.env
prisma/migrations/20220404150339_fixed_name_mappings/migration.sql
prisma/schema.prisma

.env file specified to migrate to mydb instead of graduates schema
fixed some table mappings.

🗃 (db): Fixed .env file, fixed nomenclature for some relations

---

CONTRIBUTING.md

specifically the section about making a fork and PR. 
Related to: https://github.com/COS-301/graduates/issues/286 but does not fully address the issue.

📝(docs): update the contributing guidelines

---

libs/api/shorts/repository/data-access/src/lib/ApiShortsRepository.repository.ts
prisma/migrations/20220411120856_renamed_story_to_short/migration.sql
prisma/schema.prisma

(prisma): Renamed the story tables to short tables

✅ (story): Renamed story to short

---

libs/client/companyProfile/feature/.eslintrc.json
libs/client/companyProfile/feature/README.md
libs/client/companyProfile/feature/jest.config.js
libs/client/companyProfile/feature/project.json
libs/client/companyProfile/feature/src/index.ts
libs/client/companyProfile/feature/src/lib/companyProfile-routing.module.ts
libs/client/companyProfile/feature/src/lib/companyProfile.module.ts
libs/client/companyProfile/feature/src/lib/companyProfile/companyProfile.component.html
libs/client/companyProfile/feature/src/lib/companyProfile/companyProfile.component.spec.ts
libs/client/companyProfile/feature/src/lib/companyProfile/companyProfile.component.ts
libs/client/companyProfile/feature/src/lib/editingPage/editingPage.component.html
libs/client/companyProfile/feature/src/lib/editingPage/editingPage.component.spec.ts
libs/client/companyProfile/feature/src/lib/editingPage/editingPage.component.ts
libs/client/companyProfile/feature/src/test-setup.ts
libs/client/companyProfile/feature/tsconfig.json
libs/client/companyProfile/feature/tsconfig.lib.json
libs/client/companyProfile/feature/tsconfig.spec.json

Created the Company Profile libraries and added a temporary layout for the Company Profile and editing pages to be changed later to work with angular, angular-materials, and angular-flex

✨ (ui):create CompanyProfile directory and layout

---

.github/workflows/release.yml

Workflow file for release pipeline.

✅ (CI/CD): Creation of release pipeine

---

.github/workflows/index.yml

Added the choice tag to allow for individual test running.

:white_check_mark: (CI/CD): Added choices for dispatch

---

.github/workflows/index.yml

Restructure of the index.yml to the new standard for running tests

✅(CI/CD) : Restructure of index.yml

---

.github/workflows/metatest.yml

Revised how metatest is called

:white_check_mark: (CI/CD): Removed Metatest from workflow call

---

apps/client-e2e/src/integration/app.spec.ts

Commented out mock e2e
Used as an example for people to view now

✅(CI/CD) : Removed mock e2e

---

libs/api/storage/api/feature/src/lib/api-storage.resolver.ts
libs/api/storage/api/shared/data-access/src/lib/api-storage.entity.ts
libs/api/storage/repository/data-access/src/lib/FirebaseRepository.repository.ts
libs/api/storage/repository/data-access/src/lib/StorageRepository.repository.ts
libs/api/storage/service/feature/src/lib/api-storage-service-feature.ts
package.json
yarn.lock

Added and changed functions within the StorageRepository and FirebaseRepository.

👽️✏️🔥(storage): Added access functions to the storage and firebase repository

---

apps/client-e2e/src/integration/app.spec.ts
apps/client/src/app/app-routing.module.ts
apps/client/src/app/app.component.html
apps/client/src/app/app.module.ts
libs/client/company-explore/feature/src/lib/client-company-explore-feature.module.ts
libs/client/company-explore/feature/src/lib/company-explore-feature/company-explore-banner/company-explore-banner.component.scss
libs/client/company-explore/feature/src/lib/company-explore-feature/company-explore-content/company-explore-card/company-explore-card.component.scss
libs/client/company-explore/feature/src/lib/company-explore-feature/company-explore-feature.component.scss
libs/client/company-explore/feature/src/lib/company-explore-feature/company-explore-routing.module.ts
libs/client/company-representative/feature/src/lib/client-company-representative-feature.module.ts
libs/client/company-representative/feature/src/lib/company-representative-router.module.ts
libs/client/example/feature/src/lib/feature-routing.module.ts
libs/client/example/feature/src/lib/feature.module.ts
libs/client/notifications/feature/src/lib/client-notifications-feature.module.ts
libs/client/notifications/feature/src/lib/notifications-routing.module.ts
libs/client/shorts/feature/src/lib/client-shorts-feature.module.ts
libs/client/shorts/feature/src/lib/shorts-routing.module.ts

Setup an app-router with routes to feature components using lazy loading. Added needed routing modules to before mention components where needed

🚚 (Routing): App-router and component router setup

---

prisma/migrations/20220411231721_added_companyrep_entity/migration.sql
prisma/migrations/20220412090409_added_2_entities/migration.sql
prisma/schema.prisma

Added a new entity that contains additional information for the company representative needed to be shown on the UI. 
Still references the User table. 
No other entities affected.

🗃️ (db): Added new entity for the company representative profile

---

libs/client/company-representative/feature/src/lib/company-representative-about/company-representative-about.component.html
libs/client/company-representative/feature/src/lib/company-representative-about/company-representative-about.component.scss
libs/client/company-representative/feature/src/lib/company-representative-connections/company-representative-connections.component.html
libs/client/company-representative/feature/src/lib/company-representative-connections/company-representative-connections.component.scss
libs/client/company-representative/feature/src/lib/company-representative-contact/company-representative-contact.component.html
libs/client/company-representative/feature/src/lib/company-representative-contact/company-representative-contact.component.scss
libs/client/company-representative/feature/src/lib/company-representative-experience/company-representative-experience.component.html
libs/client/company-representative/feature/src/lib/company-representative-experience/company-representative-experience.component.scss
libs/client/company-representative/feature/src/lib/company-representative-page/company-representative-page.component.scss
libs/client/company-representative/feature/src/lib/company-representative-title/company-representative-title.component.html
libs/client/company-representative/feature/src/lib/company-representative-title/company-representative-title.component.scss

Add comments to components.
Change company representative profile picture size and position.

💄 (UI) : updating company-representative-feature

---

libs/api/storage/api/feature/src/lib/api-storage.resolver.ts
libs/api/storage/api/shared/data-access/src/lib/api-storage.entity.ts
libs/api/storage/service/feature/src/lib/api-storage-service-feature.ts

-Fixed Big in The Storage Api 
-No error from Storage api

🐛 (API): Fix the Bug in API

---

.github/workflows/dev.yml

Run CI Tests for every commit to develop without affected tag

✅(CI/CD) : Added test for develop

---

libs/api/storage/api/feature/src/lib/api-storage.resolver.spec.ts
libs/api/storage/api/feature/src/lib/api-storage.resolver.ts
libs/api/storage/api/shared/data-access/src/lib/api-storage.entity.spec.ts
libs/api/storage/service/feature/src/lib/api-storage-service-feature.spec.ts

-Added The spec files in to the storage directory

✅ (API) : Added the Spec files

---

libs/api/companyprofilepage/repository/data-access/.eslintrc.json
libs/api/companyprofilepage/repository/data-access/README.md
libs/api/companyprofilepage/repository/data-access/jest.config.js
libs/api/companyprofilepage/repository/data-access/project.json
libs/api/companyprofilepage/repository/data-access/src/index.ts
libs/api/companyprofilepage/repository/data-access/src/lib/api-companyprofilepage-repository-data-access.module.ts
libs/api/companyprofilepage/repository/data-access/tsconfig.json
libs/api/companyprofilepage/repository/data-access/tsconfig.lib.json
libs/api/companyprofilepage/repository/data-access/tsconfig.spec.json
tsconfig.base.json
workspace.json
yarn.lock

Currently just the addition of the data-access files in the api library of the company profile page feature

🗃️ (repository): Added the data access files

---

.github/workflows/index.yml

Added a manual dispatch for triggering the all test.

✅ (CI/CD): Manual dispatch test all

---

.github/workflows/full.yml
.github/workflows/index.yml

All test for release, main and develop branches

✅ (CI/CD) : Full CI test

---

README.md

Added a status badge for CI affected tests

✅ (CI/CD) : Added CI Test status badge

---

libs/client/company-representative/feature/src/lib/client-company-representative-feature.module.ts
libs/client/company-representative/feature/src/lib/company-representative-routing.module.ts

router.module.ts caused NX console generation errors.
changed name to routing.module.ts with code changes to fix issue.

💄 🐛 (UI) : updating company-representative-feature

---

libs/api/companyprofilepage/repository/data-access/src/lib/api-companyprofilepage-repository.ts

Added scripts of data retrieval from the database for the company profiles

🗃️ (db-access): Database function data retrieval

---

libs/client/student-profile/feature/src/lib/achievements/achievements.component.html
libs/client/student-profile/feature/src/lib/achievements/achievements.component.sass
libs/client/student-profile/feature/src/lib/achievements/achievements.component.spec.ts
libs/client/student-profile/feature/src/lib/achievements/achievements.component.ts
libs/client/student-profile/feature/src/lib/client-student-profile-feature.module.ts
libs/client/student-profile/feature/src/lib/profile-body/profile-body.component.html

Created and implemented the base design for the "achievements" component for the profile.

💄 (Student Profile): Created base Achievements Component

---

libs/api/company-representative/repository/data-access/.eslintrc.json
libs/api/company-representative/repository/data-access/README.md
libs/api/company-representative/repository/data-access/jest.config.js
libs/api/company-representative/repository/data-access/project.json
libs/api/company-representative/repository/data-access/src/index.ts
libs/api/company-representative/repository/data-access/src/lib/api-company-representative-repository-data-access.module.ts
libs/api/company-representative/repository/data-access/src/lib/api-company-representative-repository-data-access.service.spec.ts
libs/api/company-representative/repository/data-access/src/lib/api-company-representative-repository-data-access.service.ts
libs/api/company-representative/repository/data-access/tsconfig.json
libs/api/company-representative/repository/data-access/tsconfig.lib.json
libs/api/company-representative/repository/data-access/tsconfig.spec.json
tsconfig.base.json
workspace.json

Created an explicit connection from the repository layer to our database through the PRISMA client.

👔 🌱 🚧 (repository): Create a connection from the repository layer to PRISMA

---

libs/api/shorts/api/shared/entities/data-access/src/lib/api-shorts-entity.entity.ts
libs/api/shorts/api/shared/entities/data-access/src/lib/api-shorts-tag-entity.entity.ts
libs/api/shorts/repository/data-access/src/lib/api-shorts-repository.repository.spec.ts
libs/api/shorts/repository/data-access/src/lib/api-shorts-repository.repository.ts
libs/api/shorts/service/feature/src/lib/commands/api-shorts-command-handler.handler.ts

Added all required CRUD operations and expanded shared entities. Unit testing still to be added.

✨ 🚧 (shorts): Added CRUD operations and entities

---

libs/api/companyexplore/repository/data-access/src/lib/api-companyexplore-repository-data-access.ts

Added CRUD functions so that API can retrieve data from the database
closing #706

📝(repo): Added api-companyexplore-repository-data-access.ts

---

libs/api/shorts/repository/data-access/src/lib/api-shorts-repository.repository.spec.ts
libs/api/shorts/repository/data-access/src/lib/api-shorts-repository.repository.ts

- Added unit testing for all of the CRUD operations 
- Fixed a typo

✅ ✏️ (Shorts-unit tests): Added unit testing

---

libs/api/shorts/api/shared/entities/data-access/src/lib/api-shorts-entity.entity.ts
libs/api/shorts/repository/data-access/src/lib/api-shorts-repository.repository.ts
prisma/migrations/20220414162009_update_to_short_table/migration.sql
prisma/schema.prisma

- Updated fields in the short table to be more descriptive and added the thumbnail field.
- Ensured that no operations were disrupted in the process. 
- Migrated changes made by blog team that were never migrated (checked with the blog team's data engineer that this is ok).
- Fixed typos

🎨 ✏️ 💡 🧑‍💻 (Shorts-db/API): Updated short table

---

libs/client/shared/components/buttons/ui/src/lib/button/button.component.scss

Fixed margins of UI Kit Button
@COS-301/visual-basic

:bug: (UI) UI kit: Fixed margins of  the button

---

libs/api/blog/api/shared/entities/data-access/src/lib/api-blog-comment-entity.entity.ts
libs/api/blog/api/shared/entities/data-access/src/lib/api-blog-entity.entity.ts
libs/api/blog/api/shared/entities/data-access/src/lib/api-blog-media-entity.entity.ts
libs/api/blog/repository/data-access/src/lib/api-blog-repository.repository.ts
libs/api/blog/service/feature/src/lib/api-blog-service-feature-module.module.ts
libs/api/blog/service/feature/src/lib/api-blog-service.service.ts
libs/api/blog/service/feature/src/lib/blog/queries/api-blog-query-handler.handler.ts
libs/api/blog/service/feature/src/lib/blog/queries/api-blog-query.query.ts
libs/api/blog/service/feature/src/lib/commands/api-blog-command-handler.handler.ts
libs/api/blog/service/feature/src/lib/commands/api-blog-command.command.ts
libs/api/blog/service/feature/src/lib/queries/api-blog-query-handler.handler.ts
libs/api/blog/service/feature/src/lib/queries/api-blog-query.query.ts

:white_check_mark: (service) Initial Service Commit

---

libs/api/hosting/service/feature/src/lib/api-hosting-service-feature.ts
libs/api/shell/feature/src/lib/api-shell-feature.module.ts
package.json
yarn.lock

-Added @nestjs/terminus which is required for health checks.
-Changed Code to use DI.

➕ 🎨 (Hosting) Added @nestjs/terminus and implemented DI

---

libs/client/student-profile/feature/src/lib/profile-card/profile-card.component.html
libs/client/student-profile/feature/src/lib/profile-card/profile-card.component.sass

Added an edit button to the profile-card component on the student profile page.

💄(Student Profile): Added Edit button to profile-card component

---

libs/api/storage/api/feature/src/lib/api-storage.resolver.spec.ts

-Added a few tests to the Resolver

✅ (API/Storage): Added partial Resolver Test

---

libs/api/hosting/api/shared/data-access/src/lib/api-hosting.entity.spec.ts

Added unit test for ApiHosting class

✅ (Hosting) Added unit test for ApiHosting class

---

libs/api/blog/repository/data-access/src/lib/api-blog-repository.repository.ts
libs/api/blog/service/feature/src/lib/commands/api-blog-command-handler.handler.ts
libs/api/blog/service/feature/src/lib/commands/api-blog-command.command.ts
libs/api/blog/service/feature/src/lib/queries/api-blog-query-handler.handler.ts
libs/api/blog/service/feature/src/lib/queries/api-blog-query.query.ts

Added query, query handler, command, command handler. Updated repository functions

:white_check_mark: Added query, query handler, command, command handler

---

libs/api/hosting/service/feature/src/lib/api-hosting-service-feature.ts

- was calling the incorrect method.

🐛(API/hosting) small bug fix

---

libs/api/hosting/service/feature/src/lib/api-hosting-service-feature.ts

Added health checks for the follow:
-student Explore API
-admin console API
-UP integration API

✨(API/hosting) additional health checks

---

libs/api/blog/api/feature/src/lib/api-blog-resolver.resolver.spec.ts
libs/api/blog/service/feature/src/lib/api-blog-service.service.spec.ts

Completed with the integration testing for the api-blog-resolver test, as well as updating and fixing and updating the api-blog-service test.

:white_check_mark: (Test) api-resolver blog

---

libs/api/shell/feature/src/lib/api-shell-feature.module.ts

added blog api to shell feature module

:sparkles: (api) Blog API fixes

---

libs/client/shared/components/footer/src/lib/footer/footer.component.scss
libs/client/shared/components/header/src/lib/header/header.component.scss

Updated the positioning of the header and footer to static.

:art:  (UI): UI Kit Updated positioning of header and footer.

---

libs/client/company-representative/feature/src/lib/company-representative-mock-login-page/company-representative-mock-login-page.component.html
libs/client/company-representative/feature/src/lib/company-representative-mock-login-page/company-representative-mock-login-page.component.scss
libs/client/company-representative/feature/src/lib/company-representative-page/company-representative-page.component.html

Changed stylings and page content of mock login page.
Changed real page with an additional mat-card to match edit page.

💄 (UI):updating company-representative-feature

---

libs/api/companyexplore/repository/data-access/src/lib/api-companyexplore-repository-data-access.ts

Functions used to get data from db
Closing #706

🗃️ (Repo): Create api-companyexplore-repository-data-access.ts

---

libs/client/company-representative/feature/src/lib/client-company-representative-feature.module.spec.ts
libs/client/company-representative/feature/src/lib/company-representative-page/company-representative-page.component.html
libs/client/company-representative/feature/src/lib/company-representative-page/company-representative-page.component.spec.ts
libs/client/company-representative/feature/src/lib/company-representative-page/company-representative-page.component.ts
libs/client/company-representative/feature/src/lib/company-representative-service/company-representative-service.service.spec.ts
libs/client/company-representative/feature/src/lib/company-representative-service/company-representative-service.service.ts

Added final API functionality to Company Representative Profile page.

💄(UI):Final UI

---

libs/api/hosting/service/feature/src/lib/api-hosting-service-feature.ts

-small bug fix
-cleared the hosting object

🐛(API/hosting) removed a bug

---

libs/api/upintegration/api/feature/src/lib/api-upintegration.resolver.ts
libs/api/upintegration/api/shared/data-access/src/index.ts
libs/api/upintegration/api/shared/data-access/src/lib/api-upintegration-academicrecord.entity.ts
libs/api/upintegration/api/shared/data-access/src/lib/api-upintegration-academicrecord.spec.ts
libs/api/upintegration/api/shared/data-access/src/lib/api-upintegration-studentdetails.entity.ts
libs/api/upintegration/api/shared/data-access/src/lib/api-upintegration-studentdetails.spec.ts
libs/api/upintegration/service/feature/src/lib/api-upintegration-service-feature.ts
tsconfig.base.json
workspace.json

I added the repository layer in the api to the tsconfig.base.json so that it can be referenced correctly as it did not do so when it was generated, same for the workspace.json
Added the academic record entity, and basic .spec file
Waiting on service and repository layer to finish up their sections to finish API

🎨(up-integration): expanded on academic record entity, added references

---

libs/client/company-representative/feature/src/lib/company-representative-edit-page/company-representative-edit-page.component.spec.ts
libs/client/company-representative/feature/src/lib/company-representative-edit-page/company-representative-edit-page.component.ts
libs/client/company-representative/feature/src/lib/company-representative-page/company-representative-page.component.ts
libs/client/company-representative/feature/src/lib/company-representative-service/company-representative-service.service.ts

Updated Edit Page UI to call user's current data.

💄(UI):Updated Edit Page UI

---

libs/api/blog/api/shared/entities/data-access/src/lib/api-blog-comment-entity.entity.ts
libs/api/blog/repository/data-access/src/lib/api-blog-repository.repository.spec.ts

Implementation and completion with the  blog repository test as well as a update to the comment-entity to fix a small bug found in the tests

:white_check_mark: (Test) Test for Blog Repository

---

libs/api/hosting/service/feature/src/lib/api-hosting-service-feature.spec.ts

Added tests for the get_all function in the hosting API service, other functions still have to be tested

✅ (Hosting) Added tests for hosting api service

---

libs/api/companyprofilepage/api/feature/src/index.ts
libs/api/companyprofilepage/api/feature/src/lib/api-companyprofilepage.module.ts
libs/api/companyprofilepage/api/feature/src/lib/api-companyprofilepage.resolver.ts
libs/api/companyprofilepage/api/shared/data-access/src/lib/api-companyprofilepage.entity.ts
libs/api/companyprofilepage/service/feature/src/index.ts
libs/api/companyprofilepage/service/feature/src/lib/api-companyprofilepage-service-feature.module.ts
libs/api/companyprofilepage/service/feature/src/lib/api-companyprofilepage-service-feature.ts
libs/api/companyprofilepage/service/feature/src/lib/queries/api-companyprofilepage-service-query.handler.ts
libs/api/companyprofilepage/service/feature/src/lib/queries/api-companyprofilepage-service-query.ts

Edited entities 
Added queries and query handlers

🧱 (CompanyProfilepage - api) : edited API

---

libs/api/access-status/repository/feature/src/lib/api-access-status-repository-feature.module.ts
libs/api/access-status/repository/feature/src/lib/request-access-status.repository.ts
libs/api/access-status/repository/feature/src/lib/request-access-status.spec.ts

✨ (request-for-access):Added the code for getting the status from te database

---

libs/client/company-profile/feature/src/lib/client-company-profile.module.ts
libs/client/company-profile/feature/src/lib/company-details/company-details.component.html
libs/client/company-profile/feature/src/lib/company-profile/company-profile.component.html
libs/client/company-profile/feature/src/lib/editing-page/company-bio-edit/company-bio-edit.component.html
libs/client/company-profile/feature/src/lib/editing-page/company-bio-edit/company-bio-edit.component.scss
libs/client/company-profile/feature/src/lib/editing-page/company-details-edit/company-details-edit.component.html
libs/client/company-profile/feature/src/lib/editing-page/company-details-edit/company-details-edit.component.scss
libs/client/company-profile/feature/src/lib/editing-page/industry-and-services-edit/industry-and-services-edit.component.html
libs/client/company-profile/feature/src/lib/editing-page/industry-and-services-edit/industry-and-services-edit.component.scss
libs/client/company-profile/feature/src/lib/editing-page/social-media-edit/social-media-edit.component.html
libs/client/company-profile/feature/src/lib/editing-page/social-media-edit/social-media-edit.component.scss
libs/client/company-profile/feature/src/lib/editing-page/social-media-edit/social-media-edit.component.ts
libs/client/company-profile/feature/src/lib/social-media/social-media.component.ts

Fixed button names and sizing for tablets

💄 (CompanyProfile - ui): style and sizing fixes and touch ups

---

libs/api/storage/api/feature/src/lib/api-storage.resolver.ts
libs/api/storage/repository/data-access/src/lib/StorageRepository.repository.ts

-Added the hosting check
-Fixed the check in Repository

🐛 (API) : Fix a bug

---

libs/api/companyprofilepage/repository/data-access/src/lib/api-companyprofilepage-repository.ts

Additional fetch of users who are representatives of a company query

🗃️ (CompanyProfile - repo) : Added new query

---

libs/api/companyprofilepage/api/feature/src/lib/api-companyprofilepage.module.ts
libs/api/companyprofilepage/api/feature/src/lib/api-companyprofilepage.resolver.ts
libs/api/companyprofilepage/api/shared/data-access/src/lib/api-companyprofilepage.entity.ts
libs/api/companyprofilepage/service/feature/src/lib/api-companyprofilepage-service-feature.module.ts
libs/api/companyprofilepage/service/feature/src/lib/api-companyprofilepage-service-feature.ts
libs/api/companyprofilepage/service/feature/src/lib/queries/api-companyprofilepage-service-query.handler.ts
libs/api/companyprofilepage/service/feature/src/lib/queries/api-companyprofilepage-service-query.ts

✨ (CompanyProfile - API) : Added 2 functions

---

libs/api/hosting/service/feature/src/lib/api-hosting-service-feature.spec.ts
libs/api/hosting/service/feature/src/lib/api-hosting-service-feature.ts

Improved implementation of the get_all  and implemented the checkAPIHealth function, and completed tests for the service class 
@COS-301/visual-basic

🎨 (Hosting) Improved implementation of Service, and added more tests for the service

---

libs/api/storage/api/feature/src/lib/api-storage.resolver.ts
libs/client/storage/feature/src/lib/delete-all/delete-all.component.ts
libs/client/storage/feature/src/lib/main-storage-page/main-storage-page.component.ts

-Had to update delete to be a mutation
-Updated api calls to it to be of type mutate

🐛 (API) : Update delete to be a mutation

---

libs/client/company-profile/feature/src/lib/company-bio/company-bio.component.html
libs/client/company-profile/feature/src/lib/company-bio/company-bio.component.ts
libs/client/company-profile/feature/src/lib/company-details/company-details.component.html
libs/client/company-profile/feature/src/lib/company-details/company-details.component.ts
libs/client/company-profile/feature/src/lib/company-profile/company-profile.component.ts
libs/client/company-profile/feature/src/lib/representative-list/representative-list.component.html
libs/client/company-profile/feature/src/lib/services/company-profile.service.spec.ts
libs/client/company-profile/feature/src/lib/services/company-profile.service.ts
libs/client/company-profile/feature/src/lib/social-media/social-media.component.ts

I updated the front-end to allow for the fields to be populated by the data in the database.

💄(CompanyProfile - linkage): Made the interface connect to the backend

---

libs/api/hosting/service/feature/src/lib/api-hosting-service-feature.spec.ts
libs/api/hosting/service/feature/src/lib/api-hosting-service-feature.ts

🐛 (Hosting) fixed a bug that slipped through in PR#1003, and added tests for that bug 

---

libs/api/company-representative/api/shared/data-access/src/lib/api-company-representative.entity.ts
libs/api/company-representative/repository/data-access/src/lib/company-representative.repository.ts
libs/api/storage/api/feature/src/lib/api-storage.resolver.ts
libs/api/storage/service/feature/src/lib/api-storage-service-feature.ts
libs/client/company-representative/feature/src/lib/client-company-representative-feature.module.spec.ts
libs/client/company-representative/feature/src/lib/company-representative-edit-page/company-representative-edit-page.component.spec.ts
libs/client/company-representative/feature/src/lib/company-representative-mock-login-page/company-representative-mock-login-page.component.spec.ts
libs/client/company-representative/feature/src/lib/company-representative-mock-student-explore-page/company-representative-mock-student-explore-page.component.spec.ts
libs/client/company-representative/feature/src/lib/company-representative-page/company-representative-page.component.spec.ts
libs/client/company-representative/feature/src/lib/company-representative-page/company-representative-page.component.ts
libs/client/company-representative/feature/src/lib/company-representative-service/company-representative-service.service.spec.ts
libs/client/company-representative/feature/src/lib/company-representative-service/company-representative-service.service.ts

Please note: Made changes to the to the storage team's resolver and service files to enable the integration of the company representative page with the storage team.
Additional code does not in any way break the storage team's feature

🔥 ✨ (UI): Upload & Display Picture 80% Complete

---

libs/client/shared/components/cards/ui/src/lib/cards/cards.component.scss

Updated the SCSS file to use the global.scss.

:lipstick: (UI): Updating stylesheet to use global stylesheet

---

.github/workflows/nxtest.yml
jest.preset.js
tools/scripts/merge-reports.js

Added coverage reports and linked them to [codecov](https://app.codecov.io)

✅ (CI/CD) : Jest coverage 

---

.github/workflows/nxtest.yml
jest.preset.js
tools/scripts/merge-reports.js

Added jest coverage reports in lcov format and linked to Codecov for badge usage.

✅ (CI/CD) : Added jest coverage

---

README.md

Added codecov coverage badge to README

✅ (CI/CD) : Added coverage badge

---

libs/client/company-representative/feature/src/lib/company-representative-edit-page/company-representative-edit-page.component.html
libs/client/company-representative/feature/src/lib/company-representative-edit-page/company-representative-edit-page.component.scss
libs/client/company-representative/feature/src/lib/company-representative-edit-page/company-representative-edit-page.component.spec.ts
libs/client/company-representative/feature/src/lib/company-representative-edit-page/company-representative-edit-page.component.ts
libs/client/company-representative/feature/src/lib/company-representative-mock-student-explore-page/company-representative-mock-student-explore-page.component.html
libs/client/company-representative/feature/src/lib/company-representative-mock-student-explore-page/company-representative-mock-student-explore-page.component.ts
libs/client/company-representative/feature/src/lib/company-representative-page/company-representative-page.component.html
libs/client/company-representative/feature/src/lib/company-representative-page/company-representative-page.component.scss
libs/client/company-representative/feature/src/lib/company-representative-page/company-representative-page.component.ts

Edited how the edit page form works.
Routing to real student-explore.

💄(UI):Updated Edit Page forms and routing.

---

libs/client/student-explore/feature/src/lib/client-student-explore.module.ts
libs/client/student-explore/feature/src/lib/student-card/student-card.component.html
libs/client/student-explore/feature/src/lib/student-card/student-card.component.scss
libs/client/student-explore/feature/src/lib/student-card/student-card.component.ts
libs/client/student-explore/feature/src/lib/student-explore-page/student-explore-page.component.html

- Fixed filtering by multiple fields quickly causing issues.
- Added a button to submit a filter combination
- Added pressing "enter key" to submit search request
- Fixed styling that hides "view student" button if no profile image is shown.

💄+ 🐛 (UI+Bug fixes): Bug fixes for filter, search bar and styling.

---

libs/api/companyprofilepage/repository/data-access/src/lib/api-companyprofilepage-repository.spec.ts

Addition of company profile repository spec files for tests

✅ (CompanyProfile - tests) : Repo test files added

---

libs/client/company-profile/feature/src/lib/services/company-profile.service.spec.ts

I have added tests for all the functions I created in the service file of client.

✅(CompanyProfile - tests) : added tests for service engineer code

---

apps/client/src/custom-service-worker.js

Added doxygen comments to other functions for documentation.

:memo: Added doxygen comments

---

apps/client-e2e/src/integration/app.spec.ts

- Adding request-for-access end to end test

✅ (Testing): Adding API test

---

apps/client/src/custom-service-worker.js

:memo: Doxygen, updated overview of the custom-service-worker

:memo: Doxygen, updated overview of sw

---

libs/client/shared/components/navigationbar/ui/navbar/src/lib/navigation-bar/navigation-bar.component.html
libs/client/shared/components/navigationbar/ui/navbar/src/lib/navigation-bar/navigation-bar.component.scss
libs/client/shared/components/navigationbar/ui/src/lib/navigation-bar/navigation-bar.component.html
libs/client/shared/components/navigationbar/ui/src/lib/navigation-bar/navigation-bar.component.scss

:sparkles: (UI) notification bell

---

libs/client/student-profile/feature/src/lib/achievements/achievements.component.html
libs/client/student-profile/feature/src/lib/achievements/achievements.component.ts
libs/client/student-profile/feature/src/lib/bio/bio.component.html
libs/client/student-profile/feature/src/lib/bio/bio.component.ts
libs/client/student-profile/feature/src/lib/degree/degree.component.spec.ts
libs/client/student-profile/feature/src/lib/degree/degree.component.ts
libs/client/student-profile/feature/src/lib/employment-status/employment-status.component.spec.ts
libs/client/student-profile/feature/src/lib/employment-status/employment-status.component.ts
libs/client/student-profile/feature/src/lib/location/location.component.spec.ts
libs/client/student-profile/feature/src/lib/location/location.component.ts
libs/client/student-profile/feature/src/lib/profile-body/profile-body.component.html
libs/client/student-profile/feature/src/lib/profile-card/profile-card.component.html
libs/client/student-profile/feature/src/lib/profile-card/profile-card.component.ts
libs/client/student-profile/feature/src/lib/title/title.component.spec.ts
libs/client/student-profile/feature/src/lib/title/title.component.ts
libs/client/student-profile/feature/src/lib/user-info/user-info.component.html
libs/client/student-profile/feature/src/lib/user-info/user-info.component.ts

Implemented the API calls for the UI to populate the UI.

💄(Student Profile): Implemented API calls

---

libs/client/student-profile/feature/src/lib/achievements/achievements.component.html
libs/client/student-profile/feature/src/lib/achievements/achievements.component.ts
libs/client/student-profile/feature/src/lib/bio/bio.component.html
libs/client/student-profile/feature/src/lib/bio/bio.component.ts
libs/client/student-profile/feature/src/lib/degree/degree.component.spec.ts
libs/client/student-profile/feature/src/lib/degree/degree.component.ts
libs/client/student-profile/feature/src/lib/employment-status/employment-status.component.spec.ts
libs/client/student-profile/feature/src/lib/employment-status/employment-status.component.ts
libs/client/student-profile/feature/src/lib/location/location.component.spec.ts
libs/client/student-profile/feature/src/lib/location/location.component.ts
libs/client/student-profile/feature/src/lib/profile-body/profile-body.component.html
libs/client/student-profile/feature/src/lib/profile-card/profile-card.component.html
libs/client/student-profile/feature/src/lib/profile-card/profile-card.component.ts
libs/client/student-profile/feature/src/lib/title/title.component.spec.ts
libs/client/student-profile/feature/src/lib/title/title.component.ts
libs/client/student-profile/feature/src/lib/user-info/user-info.component.html
libs/client/student-profile/feature/src/lib/user-info/user-info.component.ts

Reverts COS-301/graduates#1135

Revert "💄(Student Profile): Implemented API calls"

---

libs/client/storage/feature/src/lib/client-storage-feature.module.ts
libs/client/storage/feature/src/lib/main-storage-page/main-storage-page.component.html

Added header and footer to storage page. Storage UI functionality complete.

📝 (Storage/UI): Added header and footer to storage page.

---

libs/client/shorts/feature/src/lib/story-explore/story-explore.component.ts

- when testing please ensure there is a user with ID '123579' in the DB
- test all file formats, for video and img(mp4 and jpeg work)

:bug: (UI feature-shorts) last few bug fixes for functionality

---

libs/client/shorts/feature/src/lib/story-explore/story-explore.component.ts

this PR attempts to fix the error in [test-all / Generate cache], under client-shorts e2e teset

:bug: (UI shorts) Release/1.0.x bug fix

---

libs/api/company-representative/repository/data-access/src/lib/company-representative.repository.ts
libs/api/storage/service/feature/src/lib/api-storage-service-feature.ts
libs/client/company-representative/feature/src/lib/company-representative-page/company-representative-page.component.ts
libs/client/company-representative/feature/src/lib/company-representative-service/company-representative-service.service.ts

Removed console.log statements from 2 files.
Fixed a bug that when a user uploaded a photo twice, errors were being shown.

🐛 🔥 (UI): Fixed Upload and Display Image Bugs

---

libs/client/company-representative/feature/src/lib/company-representative-edit-page/company-representative-edit-page.component.html
libs/client/company-representative/feature/src/lib/company-representative-edit-page/company-representative-edit-page.component.ts

Fixed API call bug, given a small timeout for API to finish update call.
And removed edit page profile picture.

💄(UI):Small fix to API form call

---

libs/api/storage/service/feature/src/lib/api-storage-service-feature.ts
libs/client/storage/feature/src/lib/main-storage-page/main-storage-page.component.html
libs/client/storage/feature/src/lib/main-storage-page/main-storage-page.component.ts

Added a back button to the student profile and fixed a line mistake in the API

🏷️ 📝 (Storage/UI, Storage/API): Added a back button

---

apps/client-e2e/src/integration/app.spec.ts

Added end-2-end tests to test the full functionality of the student explore feature.

🐛(student-explore): Added e2e tests for student explore feature

---

apps/client-e2e/src/integration/app.spec.ts

Fixed conflicts and bugs from PR #1140

🐛 (Tester): Fixed e2e test issues

---

apps/client-e2e/src/integration/app.spec.ts

Re-added e2e tests that were accidentally removed by another team's PR. They might have committed an old version of the file

🐛 (student-explore): Re-added e2e tests removed by another features PR

---

libs/client/company-explore/feature/src/lib/company-explore-feature/company-explore-content/company-explore-card/company-explore-card.component.html
libs/client/company-explore/feature/src/lib/company-explore-feature/company-explore-mobile-content/company-explore-mobile-card/company-explore-mobile-card.component.html

changed my hrefs from localhost to 301graduates

🚑 (ui):change localhost:4200 to 301graduates.live in the hrefs on my cards

---

libs/client/authorization/feature/src/lib/authorization-service.service.ts

Added a window.prompt function to help us test our functionality on different UserIds

🐛 (Authorization-UI):Added a prompt

---

libs/client/student-profile/feature/src/lib/profile-card/profile-card.component.html
libs/client/student-profile/feature/src/lib/profile-routing.module.ts

Fixed the routing for the linked features to the profile namely, UP-Integration, Storage, and Shorts.

💄(Student Profile): Fixed routing for linked features

---

apps/client-e2e/src/integration/app.spec.ts

✅ (Hosting) Added e2e for api-status page

---

libs/api/upintegration/api/feature/src/lib/api-upintegration.resolver.ts
libs/client/upintegration/feature/src/lib/client-upintegration.module.ts
libs/client/upintegration/feature/src/lib/upintegration-body/upintegration-body.component.html
libs/client/upintegration/feature/src/lib/upintegration-body/upintegration-body.component.scss
libs/client/upintegration/feature/src/lib/upintegration-body/upintegration-body.component.ts

Removed imports that broke routing and corrected submit button input type.

🐛(UI): Removed unused imports and fixed button

---

libs/client/upintegration/feature/src/lib/upintegration-body/upintegration-body.component.spec.ts
libs/client/upintegration/feature/src/lib/upintegration-body/upintegration-body.component.ts

The submit button correctly gets data from API.

🐛(UI): Fixed submit button
